#╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭╮╱╱╱╱╭━┳╮╱
#┃━━╋┳┳━┳━╮╱╰╮╮┣┳┳━┳━╮╱┃╭╮┣┳┳━┳━╮╭╯┣━┳━╮┃━┫╰╮
#┣━━┃┃┃╋┃╋╰╮╭┻╯┃┃┃╋┃╋╰╮┃╭╮┃╭┫╋┃╋╰┫╋┃━┫╋╰╋━┃╭┫
#╰━━┻━┫╭┻━━╯╰━━┻━┫╭┻━━╯╰━━┻╯╰━┻━━┻━┻━┻━━┻━┻━╯
#╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱

# how often (in server ticks, 20 ticks = 1 second) should a new message be shown
interval: 1200
# should the message should be print to the console?
console-output: true

# List with messages
messages:
# list with uuid that will not get a message
dont-bug-me: