#╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭╮╱╱╱╱╭━┳╮╱
#┃━━╋┳┳━┳━╮╱╰╮╮┣┳┳━┳━╮╱┃╭╮┣┳┳━┳━╮╭╯┣━┳━╮┃━┫╰╮
#┣━━┃┃┃╋┃╋╰╮╭┻╯┃┃┃╋┃╋╰╮┃╭╮┃╭┫╋┃╋╰┫╋┃━┫╋╰╋━┃╭┫
#╰━━┻━┫╭┻━━╯╰━━┻━┫╭┻━━╯╰━━┻╯╰━┻━━┻━┻━┻━━┻━┻━╯
#╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱

# How often (in server ticks, 20 ticks = 1 second) should a new message be shown
interval: 1200

# Should the message should be print to the console?
console-output: true

# List with uuid that will not get a message
dont-bug-me: [ ]

# List with world names where messages will not be displayed (e.g. world, world_nether, world_the_end, etc.)
dont-in-worlds: [ ]

# List with messages (now you can use a %player variable)
messages: [ ]
