#╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╱╱╱╭╮╱╱╱╱╭━┳╮╱
#┃━━╋┳┳━┳━╮╱╰╮╮┣┳┳━┳━╮╱┃╭╮┣┳┳━┳━╮╭╯┣━┳━╮┃━┫╰╮
#┣━━┃┃┃╋┃╋╰╮╭┻╯┃┃┃╋┃╋╰╮┃╭╮┃╭┫╋┃╋╰┫╋┃━┫╋╰╋━┃╭┫
#╰━━┻━┫╭┻━━╯╰━━┻━┫╭┻━━╯╰━━┻╯╰━┻━━┻━┻━┻━━┻━┻━╯
#╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱

# how often (in server ticks, 20 ticks = 1 second) should a new message be shown
interval: 1200

# List with messages
messages: